### ISSUE TITLE
[EPIC] ELT Support on Fulcrum

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/cozy-sun-bear#108]
Here we are collecting use cases that emerge during discussions with Kelly Sippell.

- [ ] Set up ELT as a Publisher w/ branding
- [ ] Show previews of restricted videos for unauthorized users
- [ ] "Secondary assets" : hidden from search results, only reachable via links in metadata from some related asset (e.g. the PowerPoint that is featured in a lecture video)

**Comment by jgmorse** [comment]
Created in wrong project; re-created in https://github.com/mlibrary/heliotrope/issues/1415
