### ISSUE TITLE
Investigate event tracking

### ISSUE THREAD

**Issue by respinos** [mlibrary/cozy-sun-bear#160]
cozy-sun-bear should emit events that correspond to user interaction.

- [ ] make sure events are formatted in common fashion
- [ ] distinguish between "events" and "navigation"?
- [ ] possible to track the event that results in navigation? e.g. to emit _location has changed to $location via $navigator_ vs. _location has changed to $location via next_
