### ISSUE TITLE
Extend citation widget [EPIC]

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#49]
Extend the widget so that a user can export a citation to different citation managers. We should look at and consider support for:

- [ ] Zotero
- [ ] RefWorks
- [ ] Mendeley (already support via Sharing, but should be available here)
- [ ] EndNote
- [ ] EasyBib?
- [ ] BibTex?

This issue requires the following to proceed:
- [ ] user flows and mockups for citation export
- [ ] blocked until the completion of #39

**Comment by mbakeryo** [comment]
No longer blocked by #39
